version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: locacaotest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - '5433:5432' # porta 5433 no localhost (máquina local) mapeada para a porta 5432 do container (default pg)
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
      - '5000:3000' # porta 5000 no host (máquina local) mapeada para a porta 3000 do container
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      # - .env.prod
      - .env
    networks:
      - prisma-network # app roda na porta 3000
networks:
  prisma-network:
    name: prisma-network